# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import response_pb2 as proto_dot_response__pb2
from . import utils_pb2 as proto_dot_utils__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/utils_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UtilsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPacket = channel.unary_unary(
                '/fateark.proto.utils.UtilsService/SendPacket',
                request_serializer=proto_dot_utils__pb2.SendPacketRequest.SerializeToString,
                response_deserializer=proto_dot_response__pb2.GeneralResponse.FromString,
                _registered_method=True)
        self.GetPacketNameIDMapping = channel.unary_unary(
                '/fateark.proto.utils.UtilsService/GetPacketNameIDMapping',
                request_serializer=proto_dot_utils__pb2.GetPacketNameIDMappingRequest.SerializeToString,
                response_deserializer=proto_dot_response__pb2.GeneralResponse.FromString,
                _registered_method=True)
        self.GetClientMaintainedBotBasicInfo = channel.unary_unary(
                '/fateark.proto.utils.UtilsService/GetClientMaintainedBotBasicInfo',
                request_serializer=proto_dot_utils__pb2.GetClientMaintainedBotBasicInfoRequest.SerializeToString,
                response_deserializer=proto_dot_response__pb2.GeneralResponse.FromString,
                _registered_method=True)
        self.GetClientMaintainedExtendInfo = channel.unary_unary(
                '/fateark.proto.utils.UtilsService/GetClientMaintainedExtendInfo',
                request_serializer=proto_dot_utils__pb2.GetClientMaintainedExtendInfoRequest.SerializeToString,
                response_deserializer=proto_dot_response__pb2.GeneralResponse.FromString,
                _registered_method=True)


class UtilsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendPacket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPacketNameIDMapping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientMaintainedBotBasicInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientMaintainedExtendInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UtilsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPacket': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPacket,
                    request_deserializer=proto_dot_utils__pb2.SendPacketRequest.FromString,
                    response_serializer=proto_dot_response__pb2.GeneralResponse.SerializeToString,
            ),
            'GetPacketNameIDMapping': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPacketNameIDMapping,
                    request_deserializer=proto_dot_utils__pb2.GetPacketNameIDMappingRequest.FromString,
                    response_serializer=proto_dot_response__pb2.GeneralResponse.SerializeToString,
            ),
            'GetClientMaintainedBotBasicInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientMaintainedBotBasicInfo,
                    request_deserializer=proto_dot_utils__pb2.GetClientMaintainedBotBasicInfoRequest.FromString,
                    response_serializer=proto_dot_response__pb2.GeneralResponse.SerializeToString,
            ),
            'GetClientMaintainedExtendInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientMaintainedExtendInfo,
                    request_deserializer=proto_dot_utils__pb2.GetClientMaintainedExtendInfoRequest.FromString,
                    response_serializer=proto_dot_response__pb2.GeneralResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fateark.proto.utils.UtilsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fateark.proto.utils.UtilsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UtilsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendPacket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fateark.proto.utils.UtilsService/SendPacket',
            proto_dot_utils__pb2.SendPacketRequest.SerializeToString,
            proto_dot_response__pb2.GeneralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPacketNameIDMapping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fateark.proto.utils.UtilsService/GetPacketNameIDMapping',
            proto_dot_utils__pb2.GetPacketNameIDMappingRequest.SerializeToString,
            proto_dot_response__pb2.GeneralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientMaintainedBotBasicInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fateark.proto.utils.UtilsService/GetClientMaintainedBotBasicInfo',
            proto_dot_utils__pb2.GetClientMaintainedBotBasicInfoRequest.SerializeToString,
            proto_dot_response__pb2.GeneralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClientMaintainedExtendInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fateark.proto.utils.UtilsService/GetClientMaintainedExtendInfo',
            proto_dot_utils__pb2.GetClientMaintainedExtendInfoRequest.SerializeToString,
            proto_dot_response__pb2.GeneralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
