/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt32 GoInt;
typedef GoUint32 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_32_bit_pointer_matching_GoInt[sizeof(void*)==32/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) GoUint8 OmegaAvailable();

/* Return type for EventPoll */
struct EventPoll_return {
	char* r0; /* EventType */
	char* r1; /* RetrieverID */
};
extern __declspec(dllexport) struct EventPoll_return EventPoll();
extern __declspec(dllexport) void OmitEvent();
extern __declspec(dllexport) char* ConsumeCommandResponseCB();
extern __declspec(dllexport) void SendWebSocketCommandNeedResponse(char* cmd, char* retrieverID);
extern __declspec(dllexport) void SendPlayerCommandNeedResponse(char* cmd, char* retrieverID);
extern __declspec(dllexport) void SendWOCommand(char* cmd);
extern __declspec(dllexport) void SendWebSocketCommandOmitResponse(char* cmd);
extern __declspec(dllexport) void SendPlayerCommandOmitResponse(char* cmd);
extern __declspec(dllexport) char* SendGamePacket(GoInt packetID, char* jsonStr);

/* Return type for JsonStrAsIsGamePacketBytes */
struct JsonStrAsIsGamePacketBytes_return {
	char* r0; /* pktBytes */
	GoInt r1; /* l */
	char* r2; /* err */
};
extern __declspec(dllexport) struct JsonStrAsIsGamePacketBytes_return JsonStrAsIsGamePacketBytes(GoInt packetID, char* jsonStr);
extern __declspec(dllexport) void PlaceCommandBlock(char* option);
extern __declspec(dllexport) char* ConsumeOmegaConnError();
extern __declspec(dllexport) void ListenAllPackets();
extern __declspec(dllexport) char* GetPacketNameIDMapping();

/* Return type for ConsumeMCPacket */
struct ConsumeMCPacket_return {
	char* r0; /* packetDataAsJsonStr */
	char* r1; /* convertError */
};
extern __declspec(dllexport) struct ConsumeMCPacket_return ConsumeMCPacket();

// Bot
//
extern __declspec(dllexport) char* GetClientMaintainedBotBasicInfo();
extern __declspec(dllexport) char* GetClientMaintainedExtendInfo();
extern __declspec(dllexport) char* GetAllOnlinePlayers();
extern __declspec(dllexport) char* GetPlayerByName(char* name);
extern __declspec(dllexport) char* GetPlayerByUUID(char* uuid);
extern __declspec(dllexport) void ReleaseBindPlayer(char* uuidStr);
extern __declspec(dllexport) char* PlayerName(char* uuidStr);
extern __declspec(dllexport) GoInt64 PlayerEntityUniqueID(char* uuidStr);
extern __declspec(dllexport) GoInt64 PlayerLoginTime(char* uuidStr);
extern __declspec(dllexport) char* PlayerPlatformChatID(char* uuidStr);
extern __declspec(dllexport) GoInt32 PlayerBuildPlatform(char* uuidStr);
extern __declspec(dllexport) char* PlayerSkinID(char* uuidStr);
extern __declspec(dllexport) GoUint32 PlayerPropertiesFlag(char* uuidStr);
extern __declspec(dllexport) GoUint32 PlayerCommandPermissionLevel(char* uuidStr);
extern __declspec(dllexport) GoUint32 PlayerActionPermissions(char* uuidStr);
extern __declspec(dllexport) char* PlayerGetAbilityString(char* uuidStr);
extern __declspec(dllexport) GoUint32 PlayerOPPermissionLevel(char* uuidStr);
extern __declspec(dllexport) GoUint32 PlayerCustomStoredPermissions(char* uuidStr);
extern __declspec(dllexport) char* PlayerDeviceID(char* uuidStr);
extern __declspec(dllexport) GoUint64 PlayerEntityRuntimeID(char* uuidStr);
extern __declspec(dllexport) char* PlayerEntityMetadata(char* uuidStr);
extern __declspec(dllexport) GoUint8 PlayerIsOP(char* uuidStr);
extern __declspec(dllexport) GoUint8 PlayerOnline(char* uuidStr);
extern __declspec(dllexport) void PlayerChat(char* uuidStr, char* msg);
extern __declspec(dllexport) void PlayerTitle(char* uuidStr, char* title, char* subTitle);
extern __declspec(dllexport) void PlayerActionBar(char* uuidStr, char* actionBar);
extern __declspec(dllexport) void SetPlayerAbility(char* uuidStr, char* jsonFlags);
extern __declspec(dllexport) void InterceptPlayerJustNextInput(char* uuidStr, char* retrieverID);
extern __declspec(dllexport) char* ConsumeChat();
extern __declspec(dllexport) void ListenPlayerChange();
extern __declspec(dllexport) char* ConsumePlayerChange();
extern __declspec(dllexport) void ListenChat();
extern __declspec(dllexport) void ListenCommandBlock(char* name);
extern __declspec(dllexport) void FreeMem(void* address);
extern __declspec(dllexport) char* ConnectOmega(char* address);
extern __declspec(dllexport) char* StartOmega(char* address, char* impactOptionsJson);

#ifdef __cplusplus
}
#endif
